/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// Account information
type Account struct {
	// The timestamp when the account was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Optional email address associated with the account
	Email string `json:"email,omitempty"`
	// The timestamp of the last update to the account metadata itself (not users or creds)
	LastUpdated time.Time `json:"last_updated,omitempty"`
	// The account identifier, not updatable after creation
	Name string `json:"name"`
	// State of the account. Disabled accounts prevent member users from logging in, deleting accounts are disabled and pending deletion and will be removed once all owned resources are garbage collected by the system
	State string `json:"state,omitempty"`
	// The user type (admin vs user). If not specified in a POST request, 'user' is default
	Type_ string `json:"type,omitempty"`
}
