/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// A record of an image vulnerable to some known vulnerability. Includes vulnerable package information
type VulnerableImage struct {
	AffectedPackages []VulnerablePackageReference `json:"affected_packages,omitempty"`
	Image            *ImageReference              `json:"image,omitempty"`
}
