/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ContentJavaPackageResponseContent struct {
	ImplementationVersion string `json:"implementation-version,omitempty"`
	Location              string `json:"location,omitempty"`
	MavenVersion          string `json:"maven-version,omitempty"`
	Origin                string `json:"origin,omitempty"`
	Package_              string `json:"package,omitempty"`
	SpecificationVersion  string `json:"specification-version,omitempty"`
	Type_                 string `json:"type,omitempty"`
}
