/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// Metadata on a single feed based on what the engine finds from querying the endpoints
type FeedMetadata struct {
	// Date the metadata record was created in engine (first seen on source)
	CreatedAt    time.Time           `json:"created_at,omitempty"`
	Groups       []FeedGroupMetadata `json:"groups,omitempty"`
	LastFullSync time.Time           `json:"last_full_sync,omitempty"`
	// name of the feed
	Name string `json:"name,omitempty"`
	// Date the metadata was last updated
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
