/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ContentFilesResponseContent struct {
	Filename string `json:"filename,omitempty"`
	Gid      int32  `json:"gid,omitempty"`
	Linkdest string `json:"linkdest,omitempty"`
	Mode     string `json:"mode,omitempty"`
	Sha256   string `json:"sha256,omitempty"`
	Size     int32  `json:"size,omitempty"`
	Type_    string `json:"type,omitempty"`
	Uid      int32  `json:"uid,omitempty"`
}
