/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// System status response
type StatusResponse struct {
	Available bool         `json:"available,omitempty"`
	Busy      bool         `json:"busy,omitempty"`
	DbVersion string       `json:"db_version,omitempty"`
	Detail    *interface{} `json:"detail,omitempty"`
	Message   string       `json:"message,omitempty"`
	Up        bool         `json:"up,omitempty"`
	Version   string       `json:"version,omitempty"`
}
