/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

type EventResponseEvent struct {
	Details   *interface{}                `json:"details,omitempty"`
	Level     string                      `json:"level,omitempty"`
	Message   string                      `json:"message,omitempty"`
	Resource  *EventResponseEventResource `json:"resource,omitempty"`
	Source    *EventResponseEventSource   `json:"source,omitempty"`
	Timestamp time.Time                   `json:"timestamp,omitempty"`
	Type_     string                      `json:"type,omitempty"`
}
