/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// A summary of an image identity, including digest, id (if available), and any tags known to have ever been mapped to the digest
type ImageReference struct {
	// Timestamp, in rfc3339 format, indicating when the image state became 'analyzed' in Anchore Engine.
	AnalyzedAt string `json:"analyzed_at,omitempty"`
	// The image digest
	Digest string `json:"digest,omitempty"`
	// The image id if available
	Id         string     `json:"id,omitempty"`
	TagHistory []TagEntry `json:"tag_history,omitempty"`
}
