/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type EventResponseEventSource struct {
	BaseUrl     string `json:"base_url,omitempty"`
	Hostid      string `json:"hostid,omitempty"`
	RequestId   string `json:"request_id,omitempty"`
	Servicename string `json:"servicename,omitempty"`
}
