/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type ErrorUnknown struct{}

// Generic wrapper for metadata listings from images
type MetadataResponse struct {
	ImageDigest  string        `json:"imageDigest,omitempty"`
	Metadata     *ErrorUnknown `json:"metadata,omitempty"`
	MetadataType string        `json:"metadata_type,omitempty"`
}
