/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// A record of occurance of an asynchronous event triggered either by system or by user activity
type EventResponse struct {
	CreatedAt     time.Time           `json:"created_at,omitempty"`
	Event         *EventResponseEvent `json:"event,omitempty"`
	GeneratedUuid string              `json:"generated_uuid,omitempty"`
}
