/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

// A username, password pair that can be used to authenticate with the service as a specific user
type User struct {
	// The timestampt the user record was created
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The timestamp of the last update to this record
	LastUpdated time.Time `json:"last_updated,omitempty"`
	// The username to authenticate with
	Username string `json:"username"`
}
