/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

type FeedGroupMetadata struct {
	CreatedAt   time.Time `json:"created_at,omitempty"`
	LastSync    time.Time `json:"last_sync,omitempty"`
	Name        string    `json:"name,omitempty"`
	RecordCount int32     `json:"record_count,omitempty"`
}
