/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// A unique image in the engine.
type AnchoreImageTagSummary struct {
	AnalysisStatus string `json:"analysis_status,omitempty"`
	AnalyzedAt     int32  `json:"analyzed_at,omitempty"`
	CreatedAt      int32  `json:"created_at,omitempty"`
	Fulltag        string `json:"fulltag,omitempty"`
	ImageDigest    string `json:"imageDigest,omitempty"`
	ImageId        string `json:"imageId,omitempty"`
	TagDetectedAt  int32  `json:"tag_detected_at,omitempty"`
}
