/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// Response envelope for paginated listing of events
type EventsList struct {
	// Number of events in this page
	ItemCount int32 `json:"item_count,omitempty"`
	// Boolean flag, True indicates there are more events and False otherwise
	NextPage bool `json:"next_page,omitempty"`
	// Page number of this result set
	Page int32 `json:"page,omitempty"`
	// List of events
	Results []EventResponse `json:"results,omitempty"`
}
