/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// An account to create/add to the system. If already exists will return 400.
type AccountCreationRequest struct {
	// An optional email to associate with the account for contact purposes
	Email string `json:"email,omitempty"`
	// The account name to use. This will identify the account and must be globally unique in the system.
	Name string `json:"name"`
}
