/*
 * Anchore Engine API Server
 *
 * This is the Anchore Engine API. Provides the primary external API for users of the service.
 *
 * API version: 0.1.9
 * Contact: nurmi@anchore.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

// A login credential mapped to a user identity. For password credentials, the username to present for Basic auth is the user's username from the user record
type AccessCredential struct {
	// The timestamp of creation of the credential
	CreatedAt string `json:"created_at,omitempty"`
	// The type of credential
	Type_ string `json:"type"`
	// The credential value (e.g. the password)
	Value string `json:"value"`
}
